version: "3"

services:

  nginx:
    build: ./nginx/.
    ports:
      - 8080:80
    networks:
      - my-bridge
    volumes:
      - ./nginx/wordpress:/var/www/html
  php-fpm:
    build: ./php-fpm/.
    expose:
      - 9000
    volumes:
      - ./nginx/wordpress:/var/www/html
    networks:
      - my-bridge
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: wordpress
    volumes:
      - my-data:/var/lib/mysql
    networks:
      - my-bridge
volumes:
  my-data:
networks:
  my-bridge:
    driver: bridge
~                                                                                                                                                
~                          
