FROM centos:7
LABEL maintainer="herbiel"

ADD php-5.6.38.tar.gz /tmp
RUN yum install -y gcc gcc-c++ make gd-devel libxml2-devel libcurl-devel libjpeg-devel libpng-devel openssl-devel && \
    yum clean all && \
    cd /tmp/php-5.6.38 && \
    ./configure --prefix=/usr/local/php  --with-config-file-path=/usr/local/php/etc --with-mysql --with-mysqli --with-openssl --with-zlib --with-curl --with-gd  --with-jpeg-dir --with-png-dir --with-iconv --enable-fpm --enable-zip --enable-mbstring && \
    make -j 4 && \
    make install 
WORKDIR /usr/local/php
COPY php-fpm.conf etc/
EXPOSE 9000
CMD ["./sbin/php-fpm"]
